In [1]:
import tensorflow as tf

### 1、构建图

In [2]:
# 创建一个常量运算操作，产生一个1*2 矩阵
matrix1 = tf.constant([[3.,3.]])
# 创建另一个常量运算操作，产生一个2*1矩阵
matrix2 = tf.constant([[2.],[2.]])

In [3]:
# 创建一个矩阵乘法，把matrix1和matrix2座位输入
product = tf.matmul(matrix1,matrix2)

### 2、建立会话

In [4]:
with tf.Session() as sess:
    result = sess.run([product])
    print(result)

[array([[ 12.]], dtype=float32)]


In [ ]:
with tf.Session() as sess:
    # 指定在哪块gpu上运行
    with tf.device("/gpu:0"):
        matrix1 = tf.constant([[3.,3.]])
        matrix2 = tf.constant([[2.],[2.]])
        product = tf.matmul(matrix1,matrix2)
        sess.run(product)

### 3、变量

In [5]:
# 创建一个变量，初始化为标量0
state = tf.Variable(0,name="counter")

In [6]:
# 创建一个常量张量
input1 = tf.constant(3.0)

### 填充机制，使用tf.placeholder()临时代替任意操作的张量，在调用Session对象的run()方法执行图时，使用填充数据作为调用的参数，调用结束后填充的数据就消失

In [8]:
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)
output = tf.multiply(input1,input2)
with tf.Session() as sess:
    result = sess.run([output],feed_dict={input1:[[2.,2.]],input2:[[3.],[4.]]})
    print(result)

[array([[ 6.,  6.],
       [ 8.,  8.]], dtype=float32)]


In [9]:
with tf.Session() as sess:
    a = tf.constant([[1.0,2.0],[1.0,2.0],[1.0,2.0]])
    print(sess.run(tf.sigmoid(a)))

[[ 0.7310586   0.88079703]
 [ 0.7310586   0.88079703]
 [ 0.7310586   0.88079703]]


In [10]:
a = tf.constant([-1.0,2.0])
with tf.Session() as sess:
    b = tf.nn.relu(a)
    print(sess.run(b))

[ 0.  2.]


In [12]:
a = tf.constant([[-1.0,2.0,3.0,4.0]])
with tf.Session() as sess:
    b = tf.nn.dropout(a,0.5,noise_shape=[1,4])
    print(sess.run(b))
    b = tf.nn.dropout(a,0.5,noise_shape=[1,1])
    print(sess.run(b))

[[-2.  0.  6.  8.]]
[[-0.  0.  0.  0.]]


In [24]:
import numpy as np

In [30]:
input_data = tf.Variable(np.random.rand(10,9,9,3),dtype=np.float32)
filter_data = tf.Variable(np.random.rand(2,2,3,2),dtype=np.float32)
y = tf.nn.conv2d(input_data,filter_data,strides=[1,1,1,1],padding='SAME')

In [33]:
print(y.shape)

(10, 9, 9, 2)
